version: '3'
services:
        laravel-application:
                container_name: ${APPLICATION_NAME}-application
                build: 
                        context: ./
                        dockerfile: ./.docker/application/Dockerfile
                entrypoint: dockerize -template ./.docker/application/.env:.env -wait tcp://laravel-database:5432 -timeout 40s /bin/bash -c "dos2unix ./.docker/application/entrypoint-application.sh && ./.docker/application/entrypoint-application.sh"
                env_file: 
                        - docker.env
                volumes:
                        - .:/var/www
                networks:
                        - laravel-network 
                depends_on:
                        - laravel-database
        
        laravel-database:
                container_name: ${APPLICATION_NAME}-database
                build: 
                        context: ./
                        dockerfile: ./.docker/postgresql/Dockerfile
                tty: true
                volumes:
                        - ./.docker/dbdata:/var/lib/postgresql/data
                networks:
                        - laravel-network
                ports:
                        - 5432:5432
                environment:
                        - POSTGRES_USER=${DB_USERNAME}
                        - POSTGRES_PASSWORD=${DB_PASSWORD}
                        - POSTGRES_DB=${DB_DATABASE}
                        - POSTGRES_PORT=${DB_PORT}  
        laravel-nginx:
                container_name: ${APPLICATION_NAME}-nginx
                build: .docker/nginx
                entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf nginx -g "daemon off";
                tty: true
                env_file:
                        - docker.env
                ports:
                        - 8080:80
                volumes:
                        - .:/var/www
                networks:
                        - laravel-network
                depends_on:
                        - laravel-application

networks:
        laravel-network:
                driver: bridge
